In [104]:
import numpy as np
import pandas as pd

dotdash = pd.read_csv('/Users/Moose/desktop/programmaticAnalyst_takeHomeTest.csv', delimiter = ',')

print(dotdash.head())

  Ad unit 1         Ad unit 2  Ad unit 3     Date  Line item type Country  \
0  Lifewire  lw_buying-guides  billboard  5/20/18     Sponsorship  Canada
1  Lifewire  lw_buying-guides  billboard  5/20/18  Price priority  Canada
2  Lifewire  lw_buying-guides  billboard  5/20/18     Ad Exchange  Canada
3  Lifewire  lw_buying-guides  billboard  5/20/18               -  Canada
4  Lifewire        lw_reviews  billboard  5/20/18     Sponsorship  Canada

  Total impressions  Revenue Total Active View viewable impressions
0                32     0.91                                     24
1               777     3.00                                    520
2             1,334     7.67                                  1,196
3               253     1.43                                    194
4                 5     0.15                                      5

In [105]:
dotdash['Total impressions'] = dotdash['Total impressions'].str.replace(',','')
dotdash['Total Active View viewable impressions'] = dotdash['Total Active View viewable impressions'].str.replace(',','')
dotdash['Total impressions'] = dotdash['Total impressions'].astype(float)
dotdash['Total Active View viewable impressions'] = dotdash['Total Active View viewable impressions'].astype(float)

In [106]:
dotdash['Total impressions'].head(5)

0      32.0
1     777.0
2    1334.0
3     253.0
4       5.0
Name: Total impressions, dtype: float64

In [107]:
dotdash.dtypes

Ad unit 1                                  object
Ad unit 2                                  object
Ad unit 3                                  object
Date                                       object
Line item type                             object
Country                                    object
Total impressions                         float64
Revenue                                   float64
Total Active View viewable impressions    float64
dtype: object

In [108]:
dotdash['Line item type'].unique()

array(['Sponsorship', 'Price priority', 'Ad Exchange', '-',
       'Preferred deal', 'Standard', 'House'], dtype=object)

In [109]:
dotdash['Date'].unique()

array(['5/20/18', '5/21/18', '5/22/18', '5/23/18', '5/24/18', '5/25/18',
       '5/26/18', '5/27/18', '5/28/18', '5/29/18', '5/30/18', '5/31/18',
       '6/1/18', '6/2/18'], dtype=object)

In [110]:
dotdash['Line item type'].value_counts()

Price priority    96215
Ad Exchange       92219
-                 59598
Sponsorship       35968
Standard          20693
Preferred deal     9863
House              3344
Name: Line item type, dtype: int64

In [111]:
dotdash['Ad unit 3'].unique()

array(['billboard', 'billboard2', 'billboard3', 'billboard4',
       'billboard5', 'billboard6', 'billboard7', 'leaderboard',
       'leaderboard2', 'leaderboardac', 'leaderboardfooter',
       'leaderboardfooter2', 'adhesive', 'billboard9', 'billboardfooter',
       'billboardfooter2', 'dynamic-inline', 'native-recirc', 'video0',
       'native', nan, 'video', 'billboardmobile'], dtype=object)

In [112]:
dotdash['Ad unit 3'].value_counts()

billboard             40037
billboard2            33870
billboard3            31998
billboard4            26040
billboard5            22393
leaderboard           20839
adhesive              17714
leaderboardac         16532
leaderboardfooter     16323
billboardfooter       15529
leaderboardfooter2    14162
dynamic-inline        13625
billboardfooter2      13624
billboard6            12744
billboard7            11499
leaderboard2           8008
native                  957
video0                  746
native-recirc           723
billboardmobile         281
billboard9              196
video                    19
Name: Ad unit 3, dtype: int64

In [113]:
dotdash['Country'].unique()

array(['Canada', 'France', 'India', 'Spain', 'United Kingdom',
       'United States'], dtype=object)

In [114]:
dotdash['Country'].value_counts()

United States     109393
Canada             58239
India              51515
United Kingdom     45029
France             27012
Spain              26712
Name: Country, dtype: int64

#### Data Observations 
**Country**
- Majority of our business comes from the United States, almost 2 times that of our second biggest market Canada. 

**Ad Unit 3**
- Our most used slots are billboard, billboard2, billboard3

**Line Item Type**
- Our impressions come mainly from price priority and ad exchange

In [115]:
dotdash['cpm'] = np.where(dotdash['Total impressions'] > 0, 1000 * (dotdash['Revenue'] / dotdash['Total impressions']),
                          0)

In [116]:
dotdash['viewability'] = np.where(dotdash['Total impressions'] > 0, 
                                  dotdash['Total Active View viewable impressions'] / dotdash['Total impressions'], 0)

In [117]:
dotdash['cpm'].head(10)

0    28.437500
1     3.861004
2     5.749625
3     5.652174
4    30.000000
5     2.616822
6     5.389610
7     8.333333
8    20.000000
9     2.611940
Name: cpm, dtype: float64

In [118]:
dotdash['viewability'].head(10)

0    0.750000
1    0.669241
2    0.896552
3    0.766798
4    1.000000
5    0.532710
6    0.922078
7    0.900000
8    0.000000
9    0.574627
Name: viewability, dtype: float64

In [119]:
avg_cpm = dotdash['cpm'].mean()
print(avg_cpm)

6.13085921861

In [120]:
avg_view = dotdash['viewability'].mean()
print(avg_view)

0.53108157088

In [121]:
dotdash.groupby(dotdash['Date']).mean().sort_values(by = 'viewability', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Date,,,,,
5/20/18,180.620675,1.261972,109.137551,6.379604,0.545036
5/28/18,207.641080,1.418284,125.971997,6.191556,0.540943
5/27/18,180.742639,1.325606,108.493477,6.545150,0.539001
5/29/18,237.385126,1.618836,144.732843,5.972206,0.537451
5/22/18,217.367505,1.480462,132.253854,6.034010,0.536857
5/21/18,218.089582,1.046113,137.547089,5.458931,0.535328
5/26/18,176.862521,1.275794,105.073221,6.415287,0.534277
6/2/18,190.398490,1.451010,114.136605,7.051869,0.531025
5/25/18,201.910837,1.441808,119.605804,6.066460,0.529621
5/31/18,231.824879,1.548412,138.477874,6.309670,0.528936
5/24/18,201.088900,1.364270,119.860071,5.911250,0.526741
6/1/18,226.128290,1.692803,136.111760,6.695348,0.522283
5/30/18,240.034691,1.394351,133.027051,5.503750,0.514612
5/23/18,207.554918,1.331950,118.745244,5.618666,0.513243

In [122]:
dotdash.groupby(dotdash['Date']).mean().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Date,,,,,
6/2/18,190.398490,1.451010,114.136605,7.051869,0.531025
6/1/18,226.128290,1.692803,136.111760,6.695348,0.522283
5/27/18,180.742639,1.325606,108.493477,6.545150,0.539001
5/26/18,176.862521,1.275794,105.073221,6.415287,0.534277
5/20/18,180.620675,1.261972,109.137551,6.379604,0.545036
5/31/18,231.824879,1.548412,138.477874,6.309670,0.528936
5/28/18,207.641080,1.418284,125.971997,6.191556,0.540943
5/25/18,201.910837,1.441808,119.605804,6.066460,0.529621
5/22/18,217.367505,1.480462,132.253854,6.034010,0.536857
5/29/18,237.385126,1.618836,144.732843,5.972206,0.537451
5/24/18,201.088900,1.364270,119.860071,5.911250,0.526741
5/23/18,207.554918,1.331950,118.745244,5.618666,0.513243
5/30/18,240.034691,1.394351,133.027051,5.503750,0.514612
5/21/18,218.089582,1.046113,137.547089,5.458931,0.535328

#### Observations 
- After viewing the average CPM and Viewability for the dates (5/20/2018 - 6/2/2018), we see the the average **CPM has increased by .75** whereas the average **viewability has slightly dipped from its start at .55 to .53**

In [123]:
dotdash.groupby(dotdash['Line item type']).mean().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Line item type,,,,,
Sponsorship,129.558552,0.715163,74.855010,22.043976,0.596631
Preferred deal,121.752712,1.651428,76.393491,12.693633,0.597244
Standard,647.991301,7.929957,403.579713,11.836922,0.534172
-,85.686080,0.518543,48.976509,5.061675,0.525264
Ad Exchange,236.023141,1.591317,160.718778,3.022504,0.619111
Price priority,208.601102,0.628562,104.404646,2.136732,0.424496
House,16.156100,0.000000,4.109151,0.000000,0.354559

In [124]:
dotdash.groupby(dotdash['Line item type']).sum().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Line item type,,,,,
Sponsorship,4659962.0,25722.98,2692385.0,792877.718997,21459.627265
-,5106719.0,30904.12,2918902.0,301665.686710,31304.664931
Ad Exchange,21765818.0,146749.70,14821325.0,278732.320474,57093.801332
Standard,13408884.0,164094.61,8351275.0,244941.433850,11053.623344
Price priority,20070555.0,60477.08,10045293.0,205585.680067,40842.848907
Preferred deal,1200847.0,16288.03,753469.0,125197.305499,5890.620716
House,54026.0,0.00,13741.0,0.000000,1185.644888

#### Observation 
 **Line Item Type**
 - Sponsorship has the highest average cpm and also has the largest sum in terms of cpm
 - Ad Exchange has the highest average viewability 
 - On average standard has the highest revenue but in total Ad Exchange is the highest.

In [125]:
dotdash_usa = dotdash[dotdash['Country'] == 'United States']
dotdash_usa.head()

,Ad unit 1,Ad unit 2,Ad unit 3,Date,Line item type,Country,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
208507,Lifewire,lw_buying-guides,billboard,5/20/18,Sponsorship,United States,1253.0,32.18,1018.0,25.682362,0.812450
208508,Lifewire,lw_buying-guides,billboard,5/20/18,Preferred deal,United States,595.0,5.93,371.0,9.966387,0.623529
208509,Lifewire,lw_buying-guides,billboard,5/20/18,Standard,United States,10187.0,159.18,7928.0,15.625798,0.778247
208510,Lifewire,lw_buying-guides,billboard,5/20/18,Price priority,United States,4668.0,29.91,3088.0,6.407455,0.661525
208511,Lifewire,lw_buying-guides,billboard,5/20/18,Ad Exchange,United States,9526.0,99.99,8244.0,10.496536,0.865421

In [126]:
dotdash_usa.groupby(dotdash_usa['Date']).mean().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Date,,,,,
6/2/18,385.380429,3.820463,240.224576,11.643874,0.550338
5/26/18,348.498071,3.310451,212.837435,11.164600,0.547234
5/27/18,365.837031,3.463945,225.833597,11.056494,0.549826
5/20/18,420.871740,3.645465,260.593842,10.995131,0.549096
6/1/18,441.282657,3.942802,274.213128,10.707479,0.542895
5/28/18,422.992762,3.766656,264.126201,10.579126,0.552249
5/25/18,402.052536,3.746826,244.041020,10.476128,0.535051
5/31/18,474.742690,4.019682,292.372998,10.135283,0.535864
5/29/18,487.274378,4.225096,306.004825,10.075120,0.543664
5/24/18,441.532824,3.738282,271.300899,9.651765,0.530908
5/22/18,484.978806,4.086266,302.444714,9.474721,0.546139
5/30/18,494.963483,3.580276,273.257372,8.565433,0.500269
5/21/18,512.542598,2.894193,334.650147,8.365909,0.518829
5/23/18,454.243243,3.580599,262.330065,8.177631,0.494686

In [127]:
dotdash_international = dotdash[dotdash['Country'] != 'United States']
dotdash_international.head(5)

,Ad unit 1,Ad unit 2,Ad unit 3,Date,Line item type,Country,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
0,Lifewire,lw_buying-guides,billboard,5/20/18,Sponsorship,Canada,32.0,0.91,24.0,28.437500,0.750000
1,Lifewire,lw_buying-guides,billboard,5/20/18,Price priority,Canada,777.0,3.00,520.0,3.861004,0.669241
2,Lifewire,lw_buying-guides,billboard,5/20/18,Ad Exchange,Canada,1334.0,7.67,1196.0,5.749625,0.896552
3,Lifewire,lw_buying-guides,billboard,5/20/18,-,Canada,253.0,1.43,194.0,5.652174,0.766798
4,Lifewire,lw_reviews,billboard,5/20/18,Sponsorship,Canada,5.0,0.15,5.0,30.000000,1.000000

In [128]:
dotdash_international.groupby(dotdash_international['Date']).mean().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Date,,,,,
6/2/18,84.493455,0.164035,45.651539,4.557707,0.520535
5/22/18,87.218695,0.213168,49.484038,4.360671,0.532343
5/23/18,85.646770,0.220714,47.788665,4.354080,0.522414
5/20/18,70.142318,0.165934,39.491066,4.257174,0.543168
5/31/18,98.854001,0.195663,54.237161,4.215566,0.525143
5/21/18,82.285596,0.193764,46.641649,4.118210,0.542937
5/24/18,84.943955,0.217518,46.707520,4.104417,0.524729
5/27/18,79.854737,0.160078,44.535848,4.086188,0.533101
6/1/18,79.178258,0.156058,41.788784,3.955070,0.508205
5/28/18,94.547961,0.185023,53.419558,3.887400,0.535005
5/30/18,100.353204,0.196631,56.191557,3.826183,0.522471
5/26/18,82.543899,0.157693,45.853717,3.805404,0.527157
5/29/18,100.880219,0.195137,56.636149,3.730941,0.534057
5/25/18,92.107128,0.177206,51.336930,3.647185,0.526642

In [129]:
avg_usa_cpm = dotdash_usa['cpm'].mean()
print(avg_usa_cpm)

10.046912022

In [130]:
avg_international_cpm = dotdash_international['cpm'].mean()
print(avg_international_cpm)

4.07630582556

In [131]:
inter_sum = dotdash_international['Revenue'].sum()
print(inter_sum)

39064.49

In [132]:
usa_sum = dotdash_usa['Revenue'].sum()
print(usa_sum)

405172.02999999997

#### Observations
**Country** 
- The United States is a much larger market for us, **Generating 10X more Revenue than international markets**
- Our CPM in both USA and International has increased over the time period.
- Our viewability has stayed relatively flat over the time period.

In [133]:
dotdash.groupby(dotdash['Ad unit 1']).sum().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Ad unit 1,,,,,
Lifewire,27656353.0,158663.38,16951743.0,667108.206173,57754.672543
The Balance,11007719.0,105161.34,6699891.0,602389.207252,44924.427753
Mobile Lifewire,17462852.0,99431.88,9875850.0,345653.970043,35900.860979
Mobile The Balance,10124932.0,80873.37,6057847.0,331773.287943,30047.272587
The Balance,14955.0,106.55,11059.0,2075.474186,203.597521

In [134]:
dotdash.groupby(dotdash['Ad unit 2']).sum().sort_values(by = 'cpm', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Ad unit 2,,,,,
lw_learn-how-windows,4398514.0,25258.21,2569622.0,48088.214534,3262.216179
lw_buying-guides,6325467.0,41632.85,4040025.0,46863.762831,3658.140724
lw_web-and-search,4133782.0,24728.20,2355323.0,44391.784944,3166.917605
bal_credit-debt,1884632.0,15545.87,1215336.0,42772.219981,2828.083272
lw_learn-how-email-messaging,2954594.0,17712.05,1754363.0,42512.373958,3030.116616
bal_us-economy,3919178.0,26541.14,2205926.0,40571.937967,2872.879377
lw_learn-how-linux,935499.0,4687.51,556769.0,38909.823981,3130.665484
bal_home-buying,2236968.0,25696.54,1522367.0,38536.946298,2905.661440
lw_software-tutorials,1458261.0,8093.65,893672.0,37703.832250,2949.521912
bal_investing-for-beginners,1151024.0,9756.42,715373.0,37460.220005,2976.967102
lw_windows-troubleshooting,1228551.0,7064.19,762334.0,36922.186075,3155.412364
bal_day-trading,377974.0,3071.32,232999.0,36811.616015,2813.356870
lw_social,2255295.0,11269.37,1333094.0,36549.739985,3143.695958
lw_network-troubleshooting,615871.0,3008.09,381238.0,36452.273263,2961.129846
bal_car-insurance,875160.0,9192.84,565048.0,35867.037647,2477.626666
lw_learn-how-home-theater,1252635.0,8080.83,799133.0,35364.514476,3268.023378
lw_gaming,2462170.0,10311.19,1167180.0,35271.544002,2844.368736
bal_personal-insurance,542627.0,5600.21,338969.0,34917.856222,2546.865636
lw_web-development,403832.0,2000.15,241908.0,34538.535403,2833.311977
lw_learn-how-car-tech,1357452.0,9238.12,856544.0,34335.164093,3157.841971
bal_money-over-55,1143655.0,10311.38,628980.0,33008.409197,2582.289357
lw_software-apps,3130427.0,16840.87,1811002.0,32631.980967,3177.985856
lw_learn-how-iphone-ipod,1916065.0,11815.59,1167053.0,32487.910391,2942.189025
bal_banking,3055723.0,30999.22,1860859.0,32363.615564,3085.840145
lw_reviews,666200.0,4407.26,417577.0,31728.609561,3128.621050
lw_learn-how-macs,757991.0,4212.81,469269.0,30956.255770,2873.760120
bal_stocks,181288.0,1670.02,112815.0,30684.523321,2425.664523
bal_taxes,699181.0,7480.92,448321.0,30660.829542,2492.757377
bal_financial-software,307647.0,2622.98,196510.0,30609.982647,2294.187988
bal_mutual-funds,317086.0,3275.57,204976.0,29646.041093,2558.988705
...,...,...,...,...,...
bal_debo_refinanciar,1.0,0.01,1.0,10.000000,1.000000
bal_retail-industry,18.0,0.02,4.0,10.000000,3.000000
balev_frugal-living,30.0,0.06,7.0,9.595238,1.380952
lw_holidaytechgiftguide,20.0,0.06,2.0,9.380952,0.309524
balev_do-it-yourself,44.0,0.09,9.0,9.205794,1.025974
lw_bestsmartphoneappsforkids,182.0,0.17,1.0,7.870444,1.000000
lw_deckthehalls,109.0,0.10,0.0,6.872156,0.000000
balev_grocery-savings,15.0,0.02,0.0,6.666667,0.000000
lw_whentobuyonlinegifts,89.0,0.08,0.0,6.452815,0.000000
lw_giftsforfamily,62.0,0.06,0.0,4.446673,0.000000
lw_giftsunder100,68.0,0.07,0.0,4.445701,0.000000
lw_secretsantagifts,91.0,0.08,0.0,4.327986,0.000000
lw_lastminutegifts,74.0,0.06,0.0,3.712619,0.000000
lw_giftsforeverybudget,85.0,0.07,0.0,3.673993,0.000000
lw_holidayshoppingguide,38.0,0.04,0.0,3.416667,0.000000
balev_home-and-garden-freebies,2.0,0.00,0.0,0.000000,0.000000
balev_household-savings,3.0,0.00,0.0,0.000000,0.000000
balev_frugal-money-management,2.0,0.00,0.0,0.000000,0.000000
lw_sponsored_samsunggalaxys9accessories,10.0,0.00,1.0,0.000000,0.125000
balev_how-to-save-more-money,2.0,0.00,0.0,0.000000,0.000000
bal_project-management,48.0,0.00,2.0,0.000000,1.000000
balev_make-your-own-ingredients,2.0,0.00,0.0,0.000000,0.000000
balev_movies-and-tv-for-free,2.0,0.00,0.0,0.000000,0.000000
balev_free-samples,2.0,0.00,0.0,0.000000,0.000000
lw_sponsored_getthemostoutofyourtech,64.0,0.00,14.0,0.000000,5.116667
balev_free-printables,2.0,0.00,1.0,0.000000,1.000000
balev_contests,1.0,0.00,0.0,0.000000,0.000000
balev_frugal-beauty-and-health-care,2.0,0.00,0.0,0.000000,0.000000
bal_smartmoneymoves,0.0,0.00,0.0,0.000000,0.000000
balev_free-food,2.0,0.00,0.0,0.000000,0.000000

In [135]:
dotdash.groupby(dotdash['Ad unit 3']).sum().sort_values(by = 'Total Active View viewable impressions', ascending = False)

,Total impressions,Revenue,Total Active View viewable impressions,cpm,viewability
Ad unit 3,,,,,
billboard,13560083.0,126468.45,8583268.0,300860.413665,24275.315196
adhesive,8576203.0,55835.34,7075019.0,109201.574970,13952.342048
billboard2,8871505.0,62221.90,5365103.0,220530.975418,20699.075442
leaderboard,7010947.0,61984.19,5138605.0,174258.747550,14583.327116
billboard3,7279274.0,35913.69,3814839.0,174128.115237,16283.129412
billboard4,3378234.0,18330.45,1924272.0,146773.410508,15027.582970
dynamic-inline,3631022.0,13213.24,1858645.0,62775.061737,6389.600462
leaderboardac,2782563.0,14492.75,1506930.0,110380.575976,9090.634573
billboard5,1711029.0,9813.87,1097169.0,130637.406580,14146.472768
billboardfooter,2779091.0,12173.88,742995.0,74912.351386,4247.177764
billboard6,1069399.0,5634.77,691383.0,79639.011335,8135.311489
billboard7,751364.0,3697.87,474719.0,69461.307692,7162.231795
leaderboardfooter,1698729.0,9753.23,441329.0,111543.697817,4452.414834
native,834225.0,3821.61,359651.0,11853.762722,326.277333
billboardfooter2,1301565.0,4903.79,244902.0,58780.464758,4019.895660
leaderboardfooter2,708318.0,3933.43,211334.0,84786.734349,4225.854294
video0,116691.0,1534.52,36575.0,6360.842377,358.115183
leaderboard2,137208.0,203.84,22938.0,7982.226130,1329.680029
billboardmobile,22895.0,127.07,4967.0,1847.658111,54.095441
billboard9,13155.0,3.74,1489.0,647.958595,29.655426
native-recirc,32922.0,172.98,103.0,11234.159667,13.037690
video,83.0,0.63,67.0,230.540843,14.738834

#### Observations
**Ad units**
- billboard generates twice as much revenue as the second highest source of revenue (billboard2) 
- Native recirculation has the highest average cpm 
- Adhesive is a strong point that we should focus on
    1. It is 3rd in terms of revenue generated 
    2. It has the highest average viewable impressions
    3. Ranked 1st in terms of viewability